### ISSUE TITLE
Market is not correctly setup in setup.py

### ISSUE THREAD

**Issue by StefanBoodt** [mitchellolsthoorn/tribler#32]
#### Please, fill all relevant items:
- [ ] I have read CONTRIBUTING.md
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.
##### Tribler version/branch+revision:

michellolsthoorn/tribler/feature/market
##### Operating system and version:

Ubuntu 14.04
##### Expected behavior:

The program can run or does not crash on missing dependencies when installed with pip.
##### Actual behavior:

When using pip (which uses setup.py) to install tribler the Tribler.community.market.core package is missing and when running the market or trying to import classes an ImportError occurs.
##### Steps to reproduce the behavior:

While not having any tribler installed run:

sudo pip install git+https://github.com/mitchellolsthoorn/tribler.git@feature/market <-- install the market branch -->
python <-- Start python environment. -->
import Tribler.community.market <-- Shows succes when importing market. -->
import Tribler.community.market.core <-- core does not exist. -->
##### Relevant log file output:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named core

**Comment by StefanBoodt** [comment]
I have seen that Tribler.community.market.core is not in the packages of the setup.py. I think that adding it there would solve the problem.

**Comment by mitchellolsthoorn** [comment]
I added it to the setup.py, thx for making us aware of the problem. Let me know if it works

**Comment by StefanBoodt** [comment]
It does.
