### ISSUE TITLE
Price float bug

### ISSUE THREAD

**Issue by StefanBoodt** [mitchellolsthoorn/tribler#33]
#### Please, fill all relevant items:
- [ ] I have read CONTRIBUTING.md
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.
##### Tribler version/branch+revision:

Triller feature/market
##### Operating system and version:

Ubuntu 14.04
##### Expected behavior:

The float method in price returns a float.
##### Actual behavior:

The float method in price returns a Decimal.
##### Steps to reproduce the behavior:

Call float(price) somewhere. Additionally isinstance can be called.
##### Relevant log file output:

TypeError: **float** returned non-float (type Decimal)

**Comment by mitchellolsthoorn** [comment]
Fixed the problem,if it works close the issue please

**Comment by StefanBoodt** [comment]
I saw. It seems to work now.
